spring:
  servlet:
    multipart:
      max-file-size: 8MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          debug: true
          starttls.enable: true
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:h2:file:./db/karyeragame-db;MODE=PostgreSQL
    #url: jdbc:postgresql://localhost:5432/karyeragame
    username: admin
    driverClassName: org.h2.Driver
    #driverClassName: org.postgresql.Driver
    password: admin
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"

email:
  from: careerA.game@gmail.com

server:
  port: 8080
  servlet:
    context-path: /api/v1
application:
  security:
    jwt:
      secret-key: 123SecretKeyKeryeraGame123123SecretKeyKeryeraGame123123SecretKeyKeryeraGame123123SecretKeyKeryeraGame123
      expiration: 86400000 # millis # 1 day
      refresh-token:
        expiration: 604800000 # millis # 7 days

springdoc:
  swagger-ui:
    operationsSorter: method
  #show-oauth2-endpoints: true